version: '4'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb-url-shorten
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=1124
      - MONGO_INITDB_DATABASE=url_shorten
    volumes:
      - ./data:/data/db
